import { AppShell } from "@/components/app-shell";
import { pcbComparisons } from "@/content/pcb-comparisons";

export default function ComparisonPage() {
  return <AppShell activePath="/pcb-vs-semiconductor"><div className="mx-auto max-w-6xl px-5 py-10 pb-28 lg:px-10 lg:py-14"><p className="text-sm font-bold text-[var(--orange)]">BRIDGE YOUR EXPERIENCE</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.035em]">PCB 경험을 반도체 언어로 연결하세요.</h1><p className="mt-4 max-w-3xl leading-7 text-[var(--muted)]">기능적 공통점은 면접 답변의 출발점이 될 수 있지만, 재료·스케일·공정 조건·결함 메커니즘이 동일하다는 뜻은 아닙니다.</p>
    <div className="mt-8 rounded-2xl border border-[#f0c6ab] bg-[#fff4ed] p-5 text-sm leading-6 text-[#7d3e20]"><strong>비유 사용 원칙:</strong> “같다”가 아니라 “어떤 관점에서 유사하고, 어떤 점에서 다른지”까지 설명하세요.</div>
    <div className="mt-7 space-y-5">{pcbComparisons.map((item) => <article key={item.id} className="overflow-hidden rounded-3xl border border-[var(--line)] bg-white"><div className="grid items-center gap-4 bg-[#f5f7f3] p-5 sm:grid-cols-[1fr_auto_1fr]"><div><p className="text-[10px] font-bold tracking-wider text-[var(--muted)]">PCB</p><h2 className="mt-1 text-xl font-bold">{item.pcbConcept}</h2></div><span className="text-xl text-[var(--orange)]">↔</span><div className="sm:text-right"><p className="text-[10px] font-bold tracking-wider text-[var(--muted)]">SEMICONDUCTOR</p><h2 className="mt-1 text-xl font-bold text-[var(--green)]">{item.semiconductorConcept}</h2></div></div><div className="p-6"><p className="text-sm leading-6"><strong className="mr-2">공통 목적</strong>{item.sharedPurpose}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="text-sm font-bold text-[var(--green)]">공통점</h3><ul className="mt-3 space-y-2 text-sm text-[var(--muted)]">{item.similarities.map((text) => <li key={text}>✓ {text}</li>)}</ul></div><div><h3 className="text-sm font-bold text-[var(--orange)]">차이점</h3><ul className="mt-3 space-y-2 text-sm text-[var(--muted)]">{item.differences.map((text) => <li key={text}>• {text}</li>)}</ul></div></div><div className="mt-5 border-t border-[var(--line)] pt-4 text-sm leading-6"><strong>양산기술 관점</strong><p className="mt-1 text-[var(--muted)]">{item.productionPerspective}</p></div></div></article>)}</div>
  </div></AppShell>;
}
