import { AppShell } from "@/components/app-shell";
import { BookIcon } from "@/components/icons";
import { techPlaceholders } from "@/content/sk-hynix-tech/placeholders";
import { techConceptMap } from "@/data/tech-concept-map";
import { SK_HYNIX_TECH_CATEGORIES } from "@/types/sk-hynix-tech";

export default function SkHynixTechPage() {
  return <AppShell activePath="/sk-hynix-tech"><div className="mx-auto max-w-6xl px-5 py-10 pb-28 lg:px-10 lg:py-14">
    <div className="rounded-[2rem] bg-[var(--green)] px-6 py-9 text-white md:px-10 md:py-11"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold">OFFICIAL SOURCE CURATION</span><span className="size-1 rounded-full bg-[#a8e3b7]"/><span className="text-xs text-white/60">면접 학습용 요약</span></div><h1 className="mt-6 text-4xl font-bold tracking-[-0.04em] md:text-5xl">SK hynix Tech</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/70 md:text-base">SK hynix Newsroom의 공개 기술 자료를 공정, 수율, 양산기술 직무의 관점으로 연결합니다. 현재 카드는 실제 기사가 아닌 UI용 학습 placeholder입니다.</p></div>
    <section className="mt-8"><div className="flex flex-wrap gap-2">{SK_HYNIX_TECH_CATEGORIES.map((category) => <span key={category} className="rounded-full border border-[var(--line)] bg-white px-4 py-2 text-xs font-bold">{category}</span>)}</div></section>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_300px]"><section aria-labelledby="content-title"><div className="mb-5"><p className="text-xs font-bold tracking-[0.16em] text-[var(--orange)]">LEARNING PLACEHOLDERS</p><h2 id="content-title" className="mt-2 text-2xl font-bold">기술 학습 카드</h2></div><div className="grid gap-4 sm:grid-cols-2">{techPlaceholders.map((item) => <article key={item.id} className="rounded-2xl border border-[var(--line)] bg-white p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-[var(--mint)] px-3 py-1 text-[10px] font-bold text-[var(--green)]">{item.category}</span><span className="text-[10px] font-bold text-[var(--orange)]">PLACEHOLDER</span></div><h3 className="mt-5 text-lg font-bold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{item.description}</p><div className="mt-5 flex flex-wrap gap-2">{item.concepts.map((concept) => <span key={concept} className="rounded-md bg-[#f1f3ef] px-2 py-1 text-[10px] font-bold text-[var(--muted)]">{concept}</span>)}</div></article>)}</div><h2 className="mt-9 text-lg font-bold">Category concept map</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{SK_HYNIX_TECH_CATEGORIES.map((category) => <div key={category} className="rounded-xl border border-[var(--line)] bg-white p-4"><strong className="text-sm">{category}</strong><p className="mt-2 text-xs leading-5 text-[var(--muted)]">{techConceptMap[category]?.join(" · ") ?? "검증된 최신 Newsroom 콘텐츠"}</p></div>)}</div></section>
      <aside className="space-y-4"><div className="rounded-2xl border border-[var(--line)] bg-white p-6"><BookIcon className="size-6 text-[var(--green)]"/><h2 className="mt-5 font-bold">콘텐츠 원칙</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-[var(--muted)]"><li>• 기사 전문 대신 짧은 학습용 요약</li><li>• 실제 콘텐츠는 날짜, URL, 출처 명시</li><li>• 공개 정보와 일반 지식 구분</li><li>• 비공개 조건과 내부 수치 추정 금지</li><li>• 양산기술 관점의 질문으로 연결</li></ul></div><div className="rounded-2xl bg-[#ffe8dd] p-6"><p className="text-xs font-bold text-[#a63e16]">VERIFIED ARTICLES</p><p className="mt-3 text-3xl font-bold">0</p><p className="mt-1 text-xs leading-5 text-[#7e5747]">기사 데이터는 임의로 생성하지 않았습니다. 현재 3개 카드는 명시적 placeholder입니다.</p></div></aside>
    </div>
  </div></AppShell>;
}
