import type { PcbComparison } from "@/types/comparison";

export const pcbComparisons: readonly PcbComparison[] = [
  { id: "abf-ild", pcbConcept: "ABF", semiconductorConcept: "ILD / Low-k", sharedPurpose: "도전층 사이를 절연하고 다음 층을 형성할 기반을 제공합니다.", similarities: ["층간 절연 역할", "두께·균일도·결함 관리가 중요", "후속 via와 배선 품질에 영향"], differences: ["재료 조성과 형성 방식이 다름", "반도체는 훨씬 미세한 구조와 RC 특성을 관리", "열·기계적 신뢰성 요구 조건이 다름"], productionPerspective: "절연재 품질이 후속 공정에 연쇄 영향을 준다는 관점은 전이할 수 있지만, 동일 재료나 동일 공정으로 보면 안 됩니다." },
  { id: "pcb-via-contact", pcbConcept: "PCB Via", semiconductorConcept: "Contact / Via", sharedPurpose: "서로 다른 도전층 사이에 수직 전기 연결을 만듭니다.", similarities: ["Open과 저항 증가가 핵심 불량", "정렬, hole 형상, 충진 상태가 중요", "단면과 전기 검사 연결이 유효"], differences: ["크기와 종횡비 범위가 다름", "Contact은 소자와 첫 배선을 연결", "재료, 식각, barrier 체계가 다름"], productionPerspective: "수직 연결의 기능적 비유는 유효하지만, contact과 via의 위치 및 failure mechanism을 구분해야 합니다." },
  { id: "cu-pattern-metal", pcbConcept: "Cu Pattern", semiconductorConcept: "Metal Interconnect", sharedPurpose: "설계된 경로를 따라 신호와 전력을 전달합니다.", similarities: ["Open/short와 선폭 편차 관리", "저항과 신뢰성의 trade-off", "패턴 정렬과 검사 중요"], differences: ["반도체 배선은 다층 RC와 electromigration 영향이 큼", "패턴 형성 및 barrier 공정이 다름", "미세도와 허용 오차가 다름"], productionPerspective: "회로 패턴의 수율 관리 경험은 활용하되, 반도체 배선의 RC와 계면 신뢰성을 새로 연결해야 합니다." },
  { id: "aoi-metrology", pcbConcept: "AOI", semiconductorConcept: "Inspection / Metrology", sharedPurpose: "공정 결과를 측정해 이상을 조기에 검출하고 피드백합니다.", similarities: ["검출률과 오검출 관리", "공간 패턴을 통한 원인 추론", "공정 control과 검사 결과의 연결"], differences: ["반도체는 광학 외 전자빔·전기·박막 계측 등 범위가 넓음", "검출 대상 크기와 sampling 전략이 다름", "계측값과 결함 검사는 목적이 다름"], productionPerspective: "검사 데이터의 패턴을 공정 이력과 연결하는 문제 해결 방식은 양산기술 직무에서 강점이 됩니다." },
  { id: "build-up-beol", pcbConcept: "Layer Build-up", semiconductorConcept: "BEOL Interconnect", sharedPurpose: "절연과 도전층을 반복해 다층 연결 구조를 완성합니다.", similarities: ["층이 누적될수록 정렬과 평탄도가 중요", "하부 결함이 상부 공정에 전파", "층간 연결 신뢰성 관리"], differences: ["반도체 BEOL은 소자 위 미세 배선을 형성", "공정 온도·재료·구조 제약이 다름", "배선 계층의 전기적 설계 목표가 다름"], productionPerspective: "누적 공정의 변동 관리와 선행 품질의 중요성은 공통되지만, 스케일과 integration 제약은 구분해야 합니다." },
];
