import type { ProcessContent, ProcessStage } from "@/types/process";

const makeProcess = (
  id: string, name: string, stage: ProcessStage, order: number, summary: string,
  purpose: string, principle: string, process: string[], parameters: string[][],
  defects: string[][], troubleshooting: string[], interviewQuestions: string[],
): ProcessContent => ({
  id, name, stage, order, summary, purpose, principle, process,
  keyParameters: parameters.map(([parameterName, importance]) => ({ name: parameterName, importance })),
  typicalDefects: defects.map(([defectName, description]) => ({ name: defectName, description })),
  troubleshooting, interviewQuestions,
});

export const processes: readonly ProcessContent[] = [
  makeProcess("oxidation", "Oxidation", "FEOL", 1, "실리콘 표면에 절연 산화막을 형성합니다.", "절연, 표면 보호, 후속 공정의 마스크 역할을 위한 SiO₂ 막을 형성합니다.", "실리콘이 산화 분위기와 반응해 표면에서 산화막으로 성장합니다.", ["웨이퍼 세정", "산화 분위기에서 열처리", "막 두께 및 균일도 계측"], [["Temperature", "성장 속도와 막질에 영향을 줍니다."], ["Time", "목표 산화막 두께를 결정합니다."], ["Ambient", "건식·습식 산화의 속도와 막 특성이 달라집니다."]], [["Non-uniform oxide", "웨이퍼 내 두께 편차로 전기적 특성이 달라질 수 있습니다."], ["Interface defect", "계면 결함이 소자 신뢰성에 영향을 줄 수 있습니다."]], ["두께 맵에서 위치별 경향을 확인합니다.", "온도 균일도와 가스 공급 상태를 점검합니다.", "세정 및 표면 오염 이력을 비교합니다."], ["열산화와 증착 산화막의 차이는 무엇인가요?", "산화막 두께 편차가 소자에 어떤 영향을 줄까요?"]),
  makeProcess("photo", "Photo", "FEOL", 2, "빛을 이용해 웨이퍼 위에 회로 패턴을 전사합니다.", "후속 식각이나 주입이 선택된 영역에서만 진행되도록 패턴을 정의합니다.", "감광막의 빛 반응과 현상 선택성을 이용해 마스크 패턴을 웨이퍼로 옮깁니다.", ["감광막 도포", "정렬 및 노광", "현상", "CD와 overlay 계측"], [["Exposure dose", "패턴 크기와 형상에 영향을 줍니다."], ["Focus", "패턴 선명도와 공정 윈도우를 결정합니다."], ["Overlay", "층간 패턴 정렬 정확도를 나타냅니다."]], [["Bridge", "인접 패턴이 연결되는 결함입니다."], ["Open", "필요한 패턴이 끊기는 결함입니다."], ["Misalignment", "층간 정렬 오차입니다."]], ["CD·overlay 맵의 공간적 경향을 구분합니다.", "노광, 트랙, 마스크 요인을 분리해 확인합니다.", "전후 lot 및 장비별 변화를 비교합니다."], ["Photo 공정에서 dose와 focus의 역할은 무엇인가요?", "Overlay 이상이 수율에 미치는 영향을 설명해 보세요."]),
  makeProcess("etch", "Etch", "FEOL", 3, "마스크로 보호되지 않은 재료를 선택적으로 제거합니다.", "원하는 구조와 패턴을 하부 막에 전사합니다.", "화학 반응과 이온 충돌을 이용해 목표 막을 제거하며 선택비와 방향성을 제어합니다.", ["패턴 웨이퍼 투입", "플라즈마 또는 습식 반응", "부산물 배출", "잔사 및 프로파일 검사"], [["Selectivity", "목표막과 마스크·하부막 간 제거 속도 차이입니다."], ["Uniformity", "웨이퍼 전 영역의 식각 일관성을 나타냅니다."], ["Profile", "수직도와 구조 형상을 결정합니다."]], [["Residue", "미제거 물질이 남아 접촉 불량을 유발할 수 있습니다."], ["Over-etch", "하부막 손상이나 CD 변화가 생길 수 있습니다."]], ["결함의 center/edge 경향을 확인합니다.", "endpoint와 chamber 이력을 비교합니다.", "Photo 패턴 이상과 식각 기인 이상을 구분합니다."], ["식각 선택비가 중요한 이유는 무엇인가요?", "잔사가 발견되면 어떤 순서로 원인을 좁히겠습니까?"]),
  makeProcess("ion-implantation", "Ion Implantation", "FEOL", 4, "원하는 영역에 불순물을 주입해 전기적 특성을 조절합니다.", "트랜지스터의 source/drain과 well 등 도핑 영역을 형성합니다.", "가속된 이온을 실리콘에 주입하고 후속 열처리로 활성화합니다.", ["Photo 패턴 확인", "이온 주입", "감광막 제거", "활성화 열처리"], [["Dose", "주입되는 불순물 양을 좌우합니다."], ["Energy", "평균 주입 깊이에 영향을 줍니다."], ["Tilt", "채널링 억제와 분포 형상에 영향을 줍니다."]], [["Dose shift", "목표 농도 이탈로 전기 특성이 변할 수 있습니다."], ["Charging damage", "절연 구조에 전하 손상이 발생할 수 있습니다."]], ["전기적 계측과 장비 dose monitor를 비교합니다.", "에너지·각도 recipe와 wafer orientation을 확인합니다.", "전후 열처리 영향을 함께 검토합니다."], ["Dose와 energy는 각각 무엇을 결정하나요?", "주입 후 anneal이 필요한 이유는 무엇인가요?"]),
  makeProcess("deposition", "Deposition", "FEOL", 5, "웨이퍼 위에 필요한 재료막을 형성합니다.", "절연막, 도전막, barrier 등 소자 구조에 필요한 박막을 제공합니다.", "CVD, PVD, ALD 등 물리·화학적 방식으로 표면에 박막을 성장시킵니다.", ["표면 전처리", "전구체 또는 target 공급", "박막 형성", "두께·막질 계측"], [["Thickness", "전기·기계적 성능과 후속 공정 margin에 영향을 줍니다."], ["Conformality", "3차원 구조를 균일하게 덮는 정도입니다."], ["Film stress", "박막 변형과 박리 위험에 영향을 줍니다."]], [["Particle", "국부 단락이나 패턴 결함의 원인이 될 수 있습니다."], ["Poor coverage", "고종횡비 구조에서 연결 불량을 유발할 수 있습니다."]], ["두께·저항 맵과 chamber 누적 이력을 확인합니다.", "전구체 공급과 온도 안정성을 점검합니다.", "결함 성분 분석으로 particle source를 좁힙니다."], ["CVD, PVD, ALD의 차이를 설명해 보세요.", "Conformality가 중요한 구조의 예를 들어 보세요."]),
  makeProcess("contact", "Contact", "MOL", 6, "소자와 첫 번째 금속 배선을 전기적으로 연결합니다.", "트랜지스터 단자에서 배선층까지 낮고 안정적인 접촉을 만듭니다.", "절연막에 contact hole을 만들고 barrier 및 도전 물질로 채웁니다.", ["ILD 패터닝", "Contact hole 식각", "세정 및 barrier 형성", "금속 충진과 평탄화"], [["Contact resistance", "신호 지연과 전력 손실에 직접 연결됩니다."], ["Hole profile", "충진성과 접촉 면적에 영향을 줍니다."], ["Pre-clean", "계면 오염과 native oxide를 관리합니다."]], [["Contact open", "미충진 또는 계면 문제로 전기 연결이 끊깁니다."], ["Leakage", "인접 구조 손상이나 잔류물로 누설이 생길 수 있습니다."]], ["저항 분포와 물리적 단면 분석을 연결합니다.", "식각 잔사, pre-clean, 충진 단계를 순서대로 분리합니다.", "특정 층·위치·장비 집중 여부를 확인합니다."], ["Contact resistance 증가의 가능한 원인은 무엇인가요?", "Contact과 Via의 역할 차이를 설명해 보세요."]),
  makeProcess("dielectric", "Dielectric", "BEOL", 7, "금속 배선 사이를 전기적으로 절연합니다.", "배선 간 누설과 기생 정전용량을 줄이고 구조를 지지합니다.", "절연 재료를 증착하고 필요에 따라 경화·평탄화해 다음 배선층의 기반을 만듭니다.", ["표면 준비", "절연막 증착", "경화", "막질·두께 검사"], [["Dielectric constant", "배선 RC 지연에 영향을 줍니다."], ["Mechanical strength", "후속 공정과 패키징 신뢰성에 중요합니다."], ["Moisture", "절연 특성과 신뢰성을 저하시킬 수 있습니다."]], [["Crack", "기계적 응력으로 절연막에 균열이 생깁니다."], ["Void", "막 내부 빈 공간이 신뢰성 저하를 유발할 수 있습니다."]], ["누설과 두께/막질 계측 결과를 비교합니다.", "열 이력과 film stress 변화를 확인합니다.", "수분 및 chamber contamination 가능성을 점검합니다."], ["Low-k 물질이 필요한 이유는 무엇인가요?", "절연막의 기계적 강도가 왜 중요할까요?"]),
  makeProcess("via", "Via", "BEOL", 8, "서로 다른 금속 배선층을 수직으로 연결합니다.", "다층 배선 사이에 안정적인 전기 경로를 형성합니다.", "절연막을 패터닝·식각한 후 barrier와 도전 물질을 채워 연결 구조를 만듭니다.", ["Via 패터닝", "절연막 식각", "세정 및 barrier", "금속 충진"], [["Alignment", "하부 금속과 정확한 접속을 결정합니다."], ["Aspect ratio", "식각과 충진 난이도에 영향을 줍니다."], ["Via resistance", "배선 성능과 신뢰성을 나타냅니다."]], [["Via open", "불완전 식각이나 충진으로 연결이 끊깁니다."], ["Void", "Via 내부 미충진 영역으로 저항과 신뢰성이 악화됩니다."]], ["Open fail의 층과 공간 분포를 확인합니다.", "식각·세정·barrier·충진 결과를 단계별로 검증합니다.", "단면 분석과 전기 검사를 상호 확인합니다."], ["Via open의 원인을 어떻게 분류하겠습니까?", "고종횡비 Via가 어려운 이유는 무엇인가요?"]),
  makeProcess("metal-interconnect", "Metal Interconnect", "BEOL", 9, "소자 사이의 신호와 전력을 전달하는 금속 배선을 만듭니다.", "회로 요소를 전기적으로 연결해 설계된 기능을 구현합니다.", "금속을 형성하고 패터닝하거나 절연막 trench를 채우는 방식으로 배선을 구성합니다.", ["배선 패턴 형성", "Barrier/seed 형성", "금속 증착 또는 충진", "검사 및 평탄화"], [["Line resistance", "신호 지연과 전압 강하에 영향을 줍니다."], ["Critical dimension", "저항과 배선 간격을 결정합니다."], ["Barrier integrity", "확산과 계면 신뢰성을 좌우합니다."]], [["Open", "배선 단절로 신호가 전달되지 않습니다."], ["Short", "인접 배선 연결로 회로 오동작이 발생합니다."], ["Electromigration risk", "전류 스트레스로 장기 신뢰성이 저하될 수 있습니다."]], ["Open/short bin과 물리적 결함 위치를 연결합니다.", "CD, 두께, 저항의 상관관계를 확인합니다.", "반복 패턴과 랜덤 결함을 구분합니다."], ["배선 RC가 성능에 미치는 영향을 설명해 보세요.", "금속 배선 open과 short를 어떻게 분석하겠습니까?"]),
  makeProcess("cmp", "CMP", "BEOL", 10, "화학 반응과 기계 연마로 표면을 평탄하게 만듭니다.", "다층 배선 공정에서 다음 lithography를 위한 평탄한 표면을 제공합니다.", "Slurry의 화학 반응과 pad의 기계적 작용을 결합해 돌출된 막을 선택적으로 제거합니다.", ["Slurry 공급", "Wafer-pad 접촉 연마", "Endpoint 관리", "세정 및 표면 검사"], [["Removal rate", "생산성과 목표 두께 도달을 좌우합니다."], ["Within-wafer uniformity", "웨이퍼 내 평탄화 균일성을 나타냅니다."], ["Selectivity", "서로 다른 재료의 제거 균형을 결정합니다."]], [["Dishing", "넓은 금속 영역이 과도하게 패이는 현상입니다."], ["Erosion", "패턴 밀도가 높은 영역이 함께 낮아지는 현상입니다."], ["Scratch", "입자나 pad 상태로 표면에 흠집이 생깁니다."]], ["결함의 방향성과 위치 패턴을 확인합니다.", "Pad, slurry, conditioner 이력을 비교합니다.", "패턴 밀도 의존성과 wafer-level 균일도를 분리합니다."], ["CMP에서 화학적·기계적 작용을 설명해 보세요.", "Dishing과 erosion의 차이는 무엇인가요?"]),
];

export const processStages: readonly ProcessStage[] = ["FEOL", "MOL", "BEOL"];

export function getProcess(id: string) {
  return processes.find((process) => process.id === id);
}
